### PR TITLE
fix: an unexpected 'equal_nan' keyword argument

### PR DESCRIPTION
**Pull request by ianna**
Fixes TypeError: _unique_dispatcher() got an unexpected keyword argument 'equal_nan'

'equal_nan' was introduced from Numpy 1.24
https://numpy.org/doc/1.24/reference/generated/numpy.unique.html

### CODE REVIEW

**Review by ianna — COMMENTED** [review]
@jpivarski - please, check this PR when you have time. It is needed for @ohrechykha's PR #57 to pass. Thanks!

**Review by jpivarski — APPROVED** [review]
Without the `equal_nan` keyword argument, we can't satisfy the protocol specified by the Array API (without doing extra work with `np.isnan` to collapse multiple NaN values into a single NaN), and this was added in NumPy 1.24.

It's fine for ragged to have a tighter NumPy requirement than Awkward Array. (We don't want to increase Awkward's NumPy requirement without deliberation, since it will constrain the set of packages that can be installed in an environment.)

[NumPy 1.24 is the oldest currently-supported version of NumPy](https://endoflife.date/numpy), and even then, it will be discontinued this December.

For these reasons, I think I can merge it. Does ragged have a requirements-min.txt or similar that also needs to be updated? No, I don't see one, and NumPy is not explicitly mentioned in .readthedocs, either. Oh, but if we increase the minimum tested NumPy version in .github/workflows/ci.yml, we must also increase the actual installation constraint for PyPI. I'll do that now, and then merge after tests pass.

**Review by ianna — COMMENTED** [review]
@jpivarski - the PR cannot be auto merged because it is waiting for a required 1.22 workflow to run. I don't think, I have rights to disable it.

**Comment by jpivarski** [comment]
Got it!

**Pull request merged**
